use webadm_proftp;

ALTER TABLE quotalimits
ADD CONSTRAINT FK_quotalimits
FOREIGN KEY (nameid) REFERENCES users(userid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE quotatallies
ADD CONSTRAINT FK_quotatallies
FOREIGN KEY (nameid) REFERENCES users(userid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE userkeys
ADD CONSTRAINT FK_userkeys
FOREIGN KEY (userid) REFERENCES users(userid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE useracl
ADD CONSTRAINT FK_useracl
FOREIGN KEY (userid) REFERENCES users(userid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE useracl
ADD CONSTRAINT FK_useracl_path
FOREIGN KEY (path) REFERENCES folders(path)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE useracl
ADD CONSTRAINT FK_user_groupacl
FOREIGN KEY (groupid) REFERENCES groups(groupid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE groupacl
ADD CONSTRAINT FK_groupacl
FOREIGN KEY (groupid) REFERENCES groups(groupid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE groupacl
ADD CONSTRAINT FK_groupacl_path
FOREIGN KEY (path) REFERENCES folders(path)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE groupmembers
ADD CONSTRAINT FK_member_user
FOREIGN KEY (userid) REFERENCES users(userid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE groupmembers
ADD CONSTRAINT FK_member_group
FOREIGN KEY (groupid) REFERENCES groups(groupid)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE users AUTO_INCREMENT = 10000;
ALTER TABLE groups AUTO_INCREMENT = 10000;

INSERT INTO guiusers (username,created_by,created) VALUES ('webadm','init',NOW());
